### PR TITLE
Styling menu

### PR DESCRIPTION
**Pull request by thomschlereth**
- Add menu
- Create style.css stlyesheet

### CODE REVIEW

**Comment by thomschlereth** [comment]
@july @NickyBobby can one of you take a look at this. Should be ready to merge

**Comment by julyytran** [comment]
Great job! I think the form div needs to be adjusted to be the same height as the map and the overall width adjusted to be short enough that a user does not have to scroll over. And the neighborhoods layer button needs to be moved. I can do these changes over the weekend. 

Also, FYI my github is @julyytran

**Comment by NickyBobby** [comment]
What was the reason for changing HomeController to HomesController? Is that just better convention? Otherwise it looks fine to me. @thompickett @julyytran @kjs222

**Comment by thomschlereth** [comment]
@NickyBobby I don't even remember at this point to be honest. I can change that back. @julyytran yeah we were struggling with the height and width. The div that surrounds the map is collapsed. That would be great if you wanted to.

**Comment by thomschlereth** [comment]
@julyytran @NickyBobby I added more to it just now. It now has buttons for the transit type. Which is working locally anyway.

**Comment by NickyBobby** [comment]
I just got on that branch and checked it out locally. I think it looks really good! @thompickett

**Comment by thomschlereth** [comment]
@NickyBobby thanks, I made a few more changes I can push up. I rounded the edges of the buttons and input fields. We might want to swap out for different pics at some point, and the colors of everything needs work. Besides that I'm happy with it.

**Comment by julyytran** [comment]
Nice work, @thompickett, got us off on a great start. I agree that the menu can use more enhancement, but it's an awesome starting point. I just adjusted the height and width of things so there is no scroll bar, and fixed the map. Most changes to the map styling you'd need to put on #map, but I guess inline-block needs to be on #map-container. Not sure why, but it works now. @NickyBobby @kjs222

**Comment by thomschlereth** [comment]
@julyytran I pulled it down, it looks great! Way less obnoxious when it fits the page.

**Comment by NickyBobby** [comment]
It's looking really good. There are two things that I think should be addressed. First, some of the transportation buttons don't return results and it throws an error. Second, when you type in addresses and hit search, it reverts back to the old defaults that come with the page. I think I can help with both of these issues tomorrow. Would anyone want to get together tomorrow and work on some stuff? @julyytran @thompickett @kjs222

**Comment by NickyBobby** [comment]
Also do you want me to merge this branch, then open up a new one for those issues?

**Comment by julyytran** [comment]
@NickyBobby I can't work on it with you today, but it would be great if you could merge and work on those issues on another branch. Thanks!

**Pull request merged**
