### PR TITLE
Adds affordability layer

### PR DESCRIPTION
**Pull request by karinamzalez**
- affordability density currently hard-coded
- button added

### CODE REVIEW

**Comment by NickyBobby** [comment]
I could not figure out how to return the neighbor object from the AJAX call but we are sending the neighborhood name to the correct controller and action, and we can match up the neighborhood to find the neighborhood object. The problem is it's not responding with it correctly. @kjs222 @deborahleehamel @icorson3 @karinamzalez @chompasina @thompickett

**Comment by NickyBobby** [comment]
So I figured out the issue I was having yesterday and the neighborhoods are now being rendered with colors according to their rent price range. I adjusted the scale a little bit but may need to be played with some more. Also, the colors are probably gonna want to be changed as well. @karinamzalez @kjs222 @icorson3 @deborahleehamel @chompasina @thompickett

**Comment by NickyBobby** [comment]
There is still an issue with highlighting the neighborhoods on the map from the search results but the neighborhoods appear on the side with no issue. The JerbaScripps still needs to be worked on.

**Comment by kjs222** [comment]
Looks good.  Ready to merge.  Nick said to write this because it's his work.

**Pull request merged**
